### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by brettapeters** [googleinterns/step191-2020#30]
The current pull request template is too long. It asks for a lot of information that might not be relevant for small changes (which we want to encourage).

How can we make it better?
Should we remove it altogether?

**Comment by seanjohnite** [comment]
Maybe we could have two different templates, one for "small" changes and one for bigger features?

**Comment by aroquev00** [comment]
Yes I think it could be helpful for bigger PRs, so we could have a small one and a big one.

**Comment by thefredo1000** [comment]
But what will differ the small changes between the bigger? 
Sometimes you can change lots of lines of code and you did not change anything from the functionality. Other times one line of code can change everything.
