### ISSUE TITLE
UI/UX template

### ISSUE THREAD

**Issue by thefredo1000** [googleinterns/step191-2020#83]
We need to define a UI/UX template/library or just a certain style that we should be working on. 
Early on development @pamelalozano16 used [Material Design Lite](https://github.com/google/material-design-lite) for the index.html file.

Should we stick on that library from now on, should we look for another one or should we just develop everything by ourselves ?

**Comment by aroquev00** [comment]
I'm not very familiar with UI/UX templates, but I think the Material Design one looks cool and actually Google-y. If you guys think there are better options I'm good with that as well!

**Comment by brettapeters** [comment]
I think it would be good to have at least _some_ structure to the front end code to make your lives easier. Here are some ideas.

- Use a component library (like Material Design Lite).
- Use JSP for templating.
- Create an error page. You can map it in web.xml
- Create a common \<head> tag for all your HTML templates.
- Use JS modules https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
- Choose a CSS naming convention - like [BEM](http://getbem.com/) (the one Material Design Lite library uses).
